#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2016, Joyent, Inc.
#

#
# "sdcadm-agent" service for restoring sdcadm GZ settings on headnode reboot
# (setup) and running reboot plans in case the reboot has been fired by reboot
# plan execution.
#

set -o xtrace

. /lib/svc/share/smf_include.sh

function setup_logadm {
    # Even though our '-b cmd' creates this file, logadm rotation will not rotate
    # if the 'logs' dir and 'sdcadm.log' file don't exist.
    mkdir -p /var/log/sdcadm/logs
    touch /var/log/sdcadm/sdcadm.log

    logadm -w sdcadm_logs \
        -b '/opt/smartdc/sdcadm/tools/rotate-logs.sh -i /var/log/sdcadm/logs/ /var/log/sdcadm/sdcadm.log' \
        -t '/var/log/sdcadm/sdcadm_$nodename_%FT%H:%M:%S.log' \
        -C 168 -S 1g -p 1h \
        /var/log/sdcadm/sdcadm.log

    # Move the smf_logs entry to run last (after the entries we just added) so
    # that the default '-C' (from
    # https://github.com/joyent/smartos-live/blob/master/overlay/generic/etc/logadm.conf)
    # doesn't defeat our attempts to rotate out of "/var/svc/log".
    /usr/sbin/logadm -r smf_logs
    /usr/sbin/logadm -w smf_logs -C 8 -c -s 1m '/var/svc/log/*.log'
}


setup_logadm

# Create symlink to sdcadm.completion from /etc/bash/bash_completion.d/

if [[ -h /etc/bash/bash_completion.d/sdcadm ]]; then
	rm /etc/bash/bash_completion.d/sdcadm
fi

cd /etc/bash/bash_completion.d
ln -s /opt/smartdc/sdcadm/etc/sdcadm.completion sdcadm

exec "/usr/bin/ctrun -l child -o noorphan /opt/smartdc/sdcadm/node/bin/node --abort_on_uncaught_exception /opt/smartdc/sdcadm/lib/reboot-plan-runner.js &"

exit $SMF_EXIT_OK
