#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# "sdcadm-setup" service for restoring sdcadm GZ settings on server reboot.
#

set -o xtrace

. /lib/svc/share/smf_include.sh

# Setup log rotation.
logadm -w sdcadm_logs \
    -b '/opt/smartdc/sdcadm/tools/rotate-logs.sh -i /var/log/sdcadm/logs/ /var/log/sdcadm/sdcadm.log' \
    -t '/var/log/sdcadm/sdcadm_$nodename_%FT%H:%M:%S.log' \
    -C 168 -S 1g -p 1h \
    /var/log/sdcadm/sdcadm.log

# Even though our '-b cmd' creates this file, logadm rotation will not rotate
# if the 'logs' dir and 'sdcadm.log' file don't exist.
mkdir -p /var/log/sdcadm/logs
touch /var/log/sdcadm/sdcadm.log

exit $SMF_EXIT_OK
