#!/bin/bash
#
# Copyright (c) 2014, Joyent, Inc. All rights reserved.
#
# Make a shar for installing/upgrading sdcadm.
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail


TOP=$(cd $(dirname $0)/../ >/dev/null; pwd)
BUILD=$TOP/build/shar-image

if [[ -z "$TIMESTAMP" ]]; then
    TIMESTAMP=$(date -u "+%Y%m%dT%H%M%SZ")
fi
# Need GNU awk for multi-char arg to "-F".
AWK=$((which gawk 2>/dev/null | grep -v "^no ") || which awk)
GITDESCRIBE=g$(git describe --all --long --dirty | ${AWK} -F'-g' '{print $NF}')

VERSION=$(json -f $TOP/package.json version)
NAME=sdcadm
OUT=$TOP/$NAME-$VERSION-$TIMESTAMP-$GITDESCRIBE.sh


#---- support stuff

function fatal
{
    echo "$0: fatal error: $*" >&2
    exit 1
}

function errexit
{
    [[ $1 -ne 0 ]] || exit 0
    fatal "error exit status $1"
}


#---- mainline

trap 'errexit $?' EXIT

rm -rf $BUILD
mkdir -p $BUILD
cp -PR \
    $TOP/bin \
    $TOP/lib \
    $TOP/node_modules \
    $TOP/tools/install-sdcadm.sh \
    $TOP/package.json \
    $BUILD
cp -PR \
    $TOP/build/node \
    $BUILD/node

# Trim out cruft for smaller package.
rm -rf $BUILD/node/bin/npm
rm -rf $BUILD/node/lib/node_modules/npm
rm -rf $BUILD/node/share

# Add a stamp file to know exactly what build we have.
mkdir -p $BUILD/etc
echo "$VERSION-$TIMESTAMP-$GITDESCRIBE" >$BUILD/etc/buildstamp

TMP=/var/tmp/$NAME

(cat <<__EOF__
#!/bin/sh
#
# This shar will install/upgrade "sdcadm" on a SmartDataCenter headnode GZ.
#
function fatal {
    echo "\$0: error: \$*" >&2
    exit 3
}
[[ "\$(zonename)" == "global" ]] || fatal "not running in global zone"
[[ "\$(sysinfo | json "Boot Parameters.headnode")" == "true" ]] \
    || fatal "not running on the headnode"

echo "Extracting sdcadm $VERSION-$TIMESTAMP-$GITDESCRIBE to $TMP."

if [ \`pwd\` != '$TMP' ]; then
    rm -rf $TMP
    mkdir -p $TMP
    cd $TMP
fi

#
# The GZ where we will be unsharing does not have md5sum that the shar
# uses to verify contents.
#
mkdir -p $TMP/.temp_bin
export PATH=$TMP/.temp_bin:\$PATH
cat > $TMP/.temp_bin/md5sum << 'EOFTOOL'
__EOF__
)> $OUT

cat ./tools/md5sum-for-smartos-gz >>$OUT
(cat <<__EOF2__
EOFTOOL

chmod +x $TMP/.temp_bin/md5sum

__EOF2__
)>>$OUT


(cd $BUILD && shar -Q $(ls) | grep -v '^exit'; cat <<EOF

if [[ -n "\$TRACE" ]]; then
    export PS4="[\D{%FT%TZ}] \${BASH_SOURCE}:\${LINENO}: \${FUNCNAME[0]:+\${FUNCNAME[0]}(): }"
    set -o xtrace
fi
set -o errexit
set -o pipefail

echo "Upgrading to sdcadm $VERSION."
bash ./install-sdcadm.sh

cd /var/tmp
rm -rf $TMP

echo "Upgraded sdcadm successfully."
exit 0
EOF
)>> $OUT

echo created $OUT
