#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2015, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@$1
[[ -z "$1" ]] && echo 'rsync-to: error: no headnode given' && exit 1
BASEDIR=/opt/smartdc/sdcadm

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf $BASEDIR/node_modules
fi

for name in bin etc smf lib node_modules test package.json; do
    if [[ -d ${TOP}/$name ]]; then
        rsync -av ${TOP}/$name/ $NODE:$BASEDIR/$name/ $extraOpts
    else
        rsync -av ${TOP}/$name $NODE:$BASEDIR/$name $extraOpts
    fi
done
rsync -av ${TOP}/tools/rotate-logs.sh $NODE:$BASEDIR/tools/ $extraOpts
